# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, nixos-hardware, ... }:

{
  imports =
    [
      "${modulesPath}/installer/scan/not-detected.nix"
      nixos-hardware.nixosModules.lenovo-thinkpad-t490
      nixos-hardware.nixosModules.common-gpu-intel # preferably we'd import the coffee lake settings, but they're not exported by the nixos-hardware flake
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];

  boot.initrd.kernelModules = [ ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
